name: NodeJS with Webpack

on:
    push:
        branches: ['master']

jobs:
    build:
        env:
            platform: digital-ocean
            mongodb_uri: ${{ secrets.MONGODB_URI}}
            ssh: ${{ secrets.SSH}}

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: 'Variables de Entorno'
              if: ${{ env.platform == 'digital-ocean' }}
              run: |
                  echo "Plataforma: ${{ env.platform }}"

            - name: Deploy the app
              uses: digitalocean/app_action/deploy@v2
              with:
                  token: ${{ secrets.SSH }}

            - name: Build
              run: |
                  npm install
                  npx webpack
